Update README for updating asdf-ruby for latest ruby versions
asdf-vm/asdf-ruby pull request #303
Opened 2022-09-19 20:13 UTC by KelseyDH

This PR updates the project's README to explain how to update `asdf-ruby` to ensure the latest available versions of Ruby are available.

The documentation is not clear on what to do if ruby versions are missing from the global version list, and this confusion has already caused a few issues in the Github page, e.g:

https://github.com/asdf-vm/asdf-ruby/issues/302#issuecomment-1251442041
https://github.com/asdf-vm/asdf-ruby/issues/135#issuecomment-533797509

So hopefully this addition to the README provides a little clarity. :)

2022-09-19 20:23 UTC, Stratus3D requested changes
Thanks for the PR! Since this sentence pertains to ruby-build and getting the latest versions I think it belongs immediately above or below this sentence:

> By default asdf-ruby uses the latest release of ruby-build, but you can choose your own branch/tag through the `ASDF_RUBY_BUILD_VERSION` variable

And it is important to note that setting `ASDF_RUBY_BUILD_VERSION=master` effectively negates the need for `asdf plugin-update ruby`.

2022-09-19 20:39 UTC, KelseyDH commented
@Stratus3D Sure thing, how's this?  Trying not to be too verbose:

```
Running `asdf plugin-update ruby` will update asdf-ruby and ensure the latest versions of ruby are available to install. By default asdf-ruby uses the latest release of ruby-build, however instead you can choose your own branch/tag through the `ASDF_RUBY_BUILD_VERSION` variable:
```

2022-09-20 02:14 UTC, pboling approved these changes
LGTM

2022-09-20 12:27 UTC, Stratus3D approved these changes

2022-09-20 12:27 UTC, merged

2022-09-20 12:27 UTC, Stratus3D commented
Thanks for the PR @KelseyDH !